export const LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'