export const CREATE_EQUIPMENTS_REQUEST = 'CREATE_EQUIPMENTS_REQUEST'
export const CREATE_EQUIPMENTS_FAILED = 'CREATE_EQUIPMENTS_FAILED'
export const CREATE_EQUIPMENTS_SUCCESS = 'CREATE_EQUIPMENTS_SUCCESS'
export const RESET_CREATE_EQUIPMENTS = 'RESET_CREATE_EQUIPMENTS'

export const GET_EQUIPMENTS_SUCCESS = 'GET_EQUIPMENTS_SUCCESS'
export const GET_EQUIPMENTS_FAILED = 'GET_EQUIPMENTS_FAILED'
export const GET_EQUIPMENTS_REQUEST = 'GET_EQUIPMENTS_REQUEST'

export const GET_EQUIPMENTS_VENDOR_SUCCESS = 'GET_EQUIPMENTS_VENDOR_SUCCESS'
export const GET_EQUIPMENTS_VENDOR_FAILED = 'GET_EQUIPMENTS_VENDOR_FAILED'
export const GET_EQUIPMENTS_VENDOR_REQUEST = 'GET_EQUIPMENTS_VENDOR_REQUEST'

export const GET_EQUIPMENTS_COST_SUCCESS = 'GET_EQUIPMENTS_COST_SUCCESS'
export const GET_EQUIPMENTS_COST_FAILED = 'GET_EQUIPMENTS_COST_FAILED'
export const GET_EQUIPMENTS_COST_REQUEST = 'GET_EQUIPMENTS_COST_REQUEST'

export const GET_EQUIPMENTS_QUANTITY_SUCCESS = 'GET_EQUIPMENTS_QUANTITY_SUCCESS'
// export const GET_EQUIPMENTS_QUANTITY_FAILED = 'GET_EQUIPMENTS_QUANTITY_FAILED'
export const GET_EQUIPMENTS_QUANTITY_REQUEST = 'GET_EQUIPMENTS_COST_REQUEST'

export const GET_EQUIPMENTS_YEAR_PURCHASED_SUCCESS = 'GET_EQUIPMENTS_YEAR_PURCHASED_SUCCESS'
// export const GET_EQUIPMENTS_YEAR_PURCHASED_FAILED = 'GET_EQUIPMENTS_YEAR_PURCHASED_FAILED'
export const GET_EQUIPMENTS_YEAR_PURCHASED_REQUEST = 'GET_EQUIPMENTS_YEAR_PURCHASED_REQUEST'

export const GET_EQUIPMENTS_YEAR_EXPIRE_SUCCESS = 'GET_EQUIPMENTS_YEAR_EXPIRE_SUCCESS'
export const GET_EQUIPMENTS_YEAR_EXPIRE_FAILED = 'GET_EQUIPMENTS_YEAR_EXPIRE_FAILED'
export const GET_EQUIPMENTS_YEAR_EXPIRE_REQUEST = 'GET_EQUIPMENTS_YEAR_EXPIRE_REQUEST'

export const GET_EQUIPMENT_SUCCESS = 'GET_EQUIPMENT_SUCCESS'
export const GET_EQUIPMENT_FAILED = 'GET_EQUIPMENT_FAILED'
export const GET_EQUIPMENT_REQUEST = 'GET_EQUIPMENT_REQUEST'
