export const CREATE_INPUTS_REQUEST = 'CREATE_INPUTS_REQUEST'
export const CREATE_INPUTS_FAILED = 'CREATE_INPUTS_FAILED'
export const CREATE_INPUTS_SUCCESS = 'CREATE_INPUTS_SUCCESS'
export const RESET_CREATE_INPUTS = 'RESET_CREATE_INPUTS'

export const GET_INPUTS_SUCCESS = 'GET_INPUTS_SUCCESS'
export const GET_INPUTS_FAILED = 'GET_INPUTS_FAILED'
export const GET_INPUTS_REQUEST = 'GET_INPUTS_REQUEST'

export const GET_INPUTS_VENDOR_SUCCESS = 'GET_INPUTS_VENDOR_SUCCESS'
export const GET_INPUTS_VENDOR_FAILED = 'GET_INPUTS_VENDOR_FAILED'
export const GET_INPUTS_VENDOR_REQUEST = 'GET_INPUTS_VENDOR_REQUEST'

export const GET_INPUTS_COST_SUCCESS = 'GET_INPUTS_COST_SUCCESS'
export const GET_INPUTS_COST_FAILED = 'GET_INPUTS_COST_FAILED'
export const GET_INPUTS_COST_REQUEST = 'GET_INPUTS_COST_REQUEST'

export const GET_INPUTS_QUANTITY_SUCCESS = 'GET_INPUTS_QUANTITY_SUCCESS'
// export const GET_INPUTS_QUANTITY_FAILED = 'GET_INPUTS_QUANTITY_FAILED'
export const GET_INPUTS_QUANTITY_REQUEST = 'GET_INPUTS_COST_REQUEST'

export const GET_INPUTS_YEAR_PURCHASED_SUCCESS = 'GET_INPUTS_YEAR_PURCHASED_SUCCESS'
// export const GET_INPUTS_YEAR_PURCHASED_FAILED = 'GET_INPUTS_YEAR_PURCHASED_FAILED'
export const GET_INPUTS_YEAR_PURCHASED_REQUEST = 'GET_INPUTS_YEAR_PURCHASED_REQUEST'

export const GET_INPUTS_YEAR_ACQUIRED_SUCCESS = 'GET_INPUTS_YEAR_ACQUIRED_SUCCESS'
export const GET_INPUTS_YEAR_ACQUIRED_FAILED = 'GET_INPUTS_YEAR_ACQUIRED_FAILED'
export const GET_INPUTS_YEAR_ACQUIRED_REQUEST = 'GET_INPUTS_YEAR_ACQUIRED_REQUEST'

export const GET_INPUT_SUCCESS = 'GET_INPUT_SUCCESS'
export const GET_INPUT_FAILED = 'GET_INPUT_FAILED'
export const GET_INPUT_REQUEST = 'GET_INPUT_REQUEST'
