export const GET_PROVINCE_REQUEST = 'USER_GET_PROVINCE_REQUEST'
export const GET_PROVINCE_FAILURE = 'USER_GET_PROVINCE_FAILURE'
export const GET_PROVINCE_SUCCESS = 'USER_GET_PROVINCE_SUCCESS'

export const GET_MUNICIPALITY_REQUEST = 'USER_GET_MUNICIPALITY_REQUEST'
export const GET_MUNICIPALITY_FAILURE = 'USER_GET_MUNICIPALITY_FAILURE'
export const GET_MUNICIPALITY_SUCCESS = 'USER_GET_MUNICIPALITY_SUCCESS'

export const GET_BARANGAY_REQUEST = 'USER_GET_BARANGAY_REQUEST'
export const GET_BARANGAY_FAILURE = 'USER_GET_BARANGAY_FAILURE'
export const GET_BARANGAY_SUCCESS = 'USER_GET_BARANGAY_SUCCESS'

