

export const FETCH_AGENTS_REQUEST = 'FETCH_AGENTS_REQUEST'
export const FETCH_AGENTS_FAILED = 'FETCH_AGENTS_FAILED'
export const FETCH_AGENTS_SUCCESS = 'FETCH_AGENTS_SUCCESS'

export const FETCH_AGENTS_DOWNLINE_REQUEST = 'FETCH_AGENTS_DOWNLINE_REQUEST'
export const FETCH_AGENTS_DOWNLINE_FAILED = 'FETCH_AGENTS_DOWNLINE_FAILED'
export const FETCH_AGENTS_DOWNLINE_SUCCESS = 'FETCH_AGENTS_DOWNLINE_SUCCESS'


export const FETCH_MEMBER_LOGS_REQUEST = 'FETCH_MEMBER_LOGS_REQUEST'
export const FETCH_MEMBER_LOGS_FAILED = 'FETCH_MEMBER_LOGS_FAILED'
export const FETCH_MEMBER_LOGS_SUCCESS = 'FETCH_MEMBER_LOGS_SUCCESS'

export const FETCH_MEMBER_DETAILS_REQUEST = 'FETCH_MEMBER_DETAILS_REQUEST'
export const FETCH_MEMBER_DETAILS_FAILED = 'FETCH_MEMBER_DETAILS_FAILED'
export const FETCH_MEMBER_DETAILS_SUCCESS = 'FETCH_MEMBER_DETAILS_SUCCESS'

export const FETCH_CURRENT_USER_DETAILS_REQUEST = 'FETCH_CURRENT_USER_DETAILS_REQUEST'
export const FETCH_CURRENT_USER_DETAILS_FAILED = 'FETCH_CURRENT_USER_DETAILS_FAILED'
export const FETCH_CURRENT_USER_DETAILS_SUCCESS = 'FETCH_CURRENT_USER_DETAILS_SUCCESS'


export const PUT_MEMBER_CREDIT_REQUEST = 'PUT_MEMBER_CREDIT_REQUEST'
export const PUT_MEMBER_CREDIT_FAILED = 'PUT_MEMBER_CREDIT_FAILED'
export const PUT_MEMBER_CREDIT_SUCCESS = 'PUT_MEMBER_CREDIT_SUCCESS'
export const RESET_MEMBER_CREDIT = 'RESET_MEMBER_CREDIT'

export const FETCH_CREATE_MEMBER_REQUEST = 'FETCH_CREATE_MEMBER_REQUEST'
export const FETCH_CREATE_MEMBER_FAILED = 'FETCH_CREATE_MEMBER_FAILED'
export const FETCH_CREATE_MEMBER_SUCCESS = 'FETCH_CREATE_MEMBER_SUCCESS'

export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST'
export const ADD_MEMBER_FAILED = 'ADD_MEMBER_FAILED'
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS'
export const RESET_ADD_MEMBER_STATE = 'RESET_ADD_MEMBER_STATE'

export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST'
export const UPDATE_MEMBER_FAILED = 'UPDATE_MEMBER_FAILED'
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS'
export const RESET_UPDATE_MEMBER_STATE = 'RESET_UPDATE_MEMBER_STATE'

export const ADD_SUBUSER_REQUEST = 'ADD_SUBUSER_REQUEST'
export const ADD_SUBUSER_FAILED = 'ADD_SUBUSER_FAILED'
export const ADD_SUBUSER_SUCCESS = 'ADD_SUBUSER_SUCCESS'

export const UPDATE_SUBUSER_REQUEST = 'UPDATE_SUBUSER_REQUEST'
export const UPDATE_SUBUSER_FAILED = 'UPDATE_SUBUSER_FAILED'
export const UPDATE_SUBUSER_SUCCESS = 'UPDATE_SUBUSER_SUCCESS'
export const RESET_UPDATE_SUBUSER_STATE = 'RESET_UPDATE_SUBUSER_STATE'

export const RESET_ADD_SUBUSER_STATE = 'RESET_ADD_SUBUSER_STATE'
export const FETCH_SUBUSER_REQUEST = 'FETCH_SUBUSER_REQUEST'
export const FETCH_SUBUSER_FAILED = 'FETCH_SUBUSER_FAILED'
export const FETCH_SUBUSER_SUCCESS = 'FETCH_SUBUSER_SUCCESS'

export const FETCH_SINGLE_SUBUSER_REQUEST = 'FETCH_SINGLE_SUBUSER_REQUEST'
export const FETCH_SINGLE_SUBUSER_FAILED = 'FETCH_SINGLE_SUBUSER_FAILED'
export const FETCH_SINGLE_SUBUSER_SUCCESS = 'FETCH_SINGLE_SUBUSER_SUCCESS'
export const UPDATE_SINGLE_SUBUSER = 'UPDATE_SINGLE_SUBUSER'

export const FETCH_SUBUSERUSERNAME_REQUEST = 'FETCH_SUBUSERUSERNAME_REQUEST'
export const FETCH_SUBUSERUSERNAME_FAILED = 'FETCH_SUBUSERUSERNAME_FAILED'
export const FETCH_SUBUSERUSERNAME_SUCCESS = 'FETCH_SUBUSERUSERNAME_SUCCESS'

export const UPDATE_USER_STATUS_REQUEST = 'UPDATE_USER_STATUS_REQUEST'
export const UPDATE_USER_STATUS_FAILED = 'UPDATE_USER_STATUS_FAILED'
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS'

export const FETCH_COPY_USER_REQUEST = 'FETCH_COPY_USER_REQUEST'
export const FETCH_COPY_USER_FAILED = 'FETCH_COPY_USER_FAILED'
export const FETCH_COPY_USER_SUCCESS = 'FETCH_COPY_USER_SUCCESS'
export const RESET_COPY_USER = 'RESET_COPY_USER'

export const ADD_COPY_USER_REQUEST = 'ADD_COPY_USER_REQUEST'
export const ADD_COPY_USER_FAILED = 'ADD_COPY_USER_FAILED'
export const ADD_COPY_USER_SUCCESS = 'ADD_COPY_USER_SUCCESS'
export const RESET_ADD_COPY_USER = 'RESET_ADD_COPY_USER'

export const FETCH_PTSETTING_REQUEST = 'FETCH_PTSETTING_REQUEST'
export const FETCH_PTSETTING_FAILED = 'FETCH_PTSETTING_FAILED'
export const FETCH_PTSETTING_SUCCESS = 'FETCH_PTSETTING_SUCCESS'
export const RESET_PTSETTING = 'RESET_PTSETTING'
export const RESET_PTSETTING_EDIT = 'RESET_PTSETTING_EDIT'
export const EDIT_PTSETTING_REQUEST = 'EDIT_PTSETTING_REQUEST'
export const EDIT_PTSETTING_FAILED = 'EDIT_PTSETTING_FAILED'
export const EDIT_PTSETTING_SUCCESS = 'EDIT_PTSETTING_SUCCESS'

export const RESET_USERLIST = 'RESET_USERLIST'
export const RESET_DOWNLINE_USERLIST = 'RESET_DOWNLINE_USERLIST'

export const FETCH_NEW_USERS_REQUEST = 'FETCH_NEW_USERS_REQUEST'
export const FETCH_NEW_USERS_FAILED = 'FETCH_NEW_USERS_FAILED'
export const FETCH_NEW_USERS_SUCCESS = 'FETCH_NEW_USERS_SUCCESS'

export const FETCH_MEMBER_HIERARCHY_REQUEST = 'FETCH_MEMBER_HIERARCHY_REQUEST'
export const FETCH_MEMBER_HIERARCHY_FAILED = 'FETCH_MEMBER_HIERARCHY_FAILED'
export const FETCH_MEMBER_HIERARCHY_SUCCESS = 'FETCH_MEMBER_HIERARCHY_SUCCESS'


export const FETCH_MEMBER_TOTAL_OUTSTANDING_REQUEST = 'FETCH_MEMBER_TOTAL_OUTSTANDING_REQUEST'
export const FETCH_MEMBER_TOTAL_OUTSTANDING_FAILED = 'FETCH_MEMBER_TOTAL_OUTSTANDING_FAILED'
export const FETCH_MEMBER_TOTAL_OUTSTANDING_SUCCESS = 'FETCH_MEMBER_TOTAL_OUTSTANDING_SUCCESS'
export const RESET_MEMBER_TOTAL_OUTSTANDING = 'RESET_MEMBER_TOTAL_OUTSTANDING'

