export const REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const REGISTER_FAILURE = 'USER_REGISTER_FAILURE'
export const REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'