export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST'
export const CREATE_EXPENSE_FAILED = 'CREATE_EXPENSE_FAILED'
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'
export const RESET_CREATE_EXPENSE = 'RESET_CREATE_EXPENSE'

export const CREATE_INCOME_REQUEST = 'CREATE_INCOME_REQUEST'
export const CREATE_INCOME_FAILED = 'CREATE_INCOME_FAILED'
export const CREATE_INCOME_SUCCESS = 'CREATE_INCOME_SUCCESS'
export const RESET_CREATE_INCOME = 'RESET_CREATE_INCOME'

export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS'
export const GET_INCOME_FAILED = 'GET_INCOME_FAILED'
export const GET_INCOME_REQUEST = 'GET_INCOME_REQUEST'

export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESS'
export const GET_EXPENSE_FAILED = 'GET_EXPENSE_FAILED'
export const GET_EXPENSE_REQUEST = 'GET_EXPENSE_REQUEST'

