export const CREATE_DRINKS_REQUEST = 'CREATE_DRINKS_REQUEST'
export const CREATE_DRINKS_FAILED = 'CREATE_DRINKS_FAILED'
export const CREATE_DRINKS_SUCCESS = 'CREATE_DRINKS_SUCCESS'
export const RESET_CREATE_DRINKS = 'RESET_CREATE_DRINKS'

export const GET_DRINKS_SUCCESS = 'GET_DRINKS_REQUEST'
export const GET_DRINKS_FAILED = 'GET_DRINKS_FAILED'
export const GET_DRINKS_REQUEST = 'GET_DRINKS_SUCCESS'

export const GET_DRINKS_YEAR_SUCCESS = 'GET_DRINKS_YEAR_REQUEST'
export const GET_DRINKS_YEAR_FAILED = 'GET_DRINKS_YEAR_FAILED'
export const GET_DRINKS_YEAR_REQUEST = 'GET_DRINKS_YEAR_SUCCESS'

export const GET_DRINKS_VINEYARD_SUCCESS = 'GET_DRINKS_YEAR_VINEYARD'
export const GET_DRINKS_VINEYARD_FAILED = 'GET_DRINKS_YEAR_VINEYARD'
export const GET_DRINKS_VINEYARD_REQUEST = 'GET_DRINKS_YEAR_VINEYARD'

export const GET_DRINK_SUCCESS = 'GET_DRINK_REQUEST'
export const GET_DRINK_FAILED = 'GET_DRINK_FAILED'
export const GET_DRINK_REQUEST = 'GET_DRINK_SUCCESS'
